Re-enable the ability to run tests using RBE. (#1378)
Setting `exec_properties` on `//test:python_test` is required when running on the CI via Github actions, but fails when running on RBE with:

```
ERROR: /usr/local/google/home/mumak/github.com/mum4k/nighthawk/test/BUILD:317:14: Compiling test/python_test.cc failed: (Exit 34): FAILED_PRECONDITION: there are no bots capable of executing the action, requested action properties: Pool = linux_x64_large, OSFamily = Linux
java.io.IOException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: there are no bots capable of executing the action, requested action properties: Pool = linux_x64_large, OSFamily = Linux
```

This is because the pool `linux_x64_large` isn't defined on RBE.

Making the `exec_properties` conditional (a `select`) that sets it only when running on Github actions. This is determined via a new custom flag.

Signed-off-by: Jakub Sobon <mumak@google.com>