exceptions: Catch all exceptions by const reference
Currently, `bazel build //:nighthawk` fails with the error below. The changes in this commit allow bazel build to pass. This also follows standard practices for C++.

```
error: catching polymorphic type 'class Nighthawk::Client::MalformedArgvException' by value [-Werror=catch-value=]
```

Signed-off-by: Teju Nareddy <nareddyt@google.com>