support non-default buildifier/buildozer paths (#341)
When buildifier or buildozer can't be found, these instructions are printed:

```
ERROR: Command /usr/local/bin/buildifier not found. If you have buildifier installed, but the binary name is different or it's not available in $GOPATH/bin, please use BUILDIFIER_BIN environment variable to specify the path. Example:
    export BUILDIFIER_BIN=`which buildifier`
If you don't have buildifier installed, you can install it by:
    go get -u github.com/bazelbuild/buildtools/buildifier
ERROR: Command /usr/local/bin/buildozer not found. If you have buildozer installed, but the binary name is different or it's not available in $GOPATH/bin, please use BUILDOZER_BIN environment variable to specify the path. Example:
    export BUILDOZER_BIN=`which buildozer`
If you don't have buildozer installed, you can install it by:
    go get -u github.com/bazelbuild/buildtools/buildozer
```

After doing the `go get` and  `export`, we still get the same message.

It turns out do_ci.sh unconditionally overwrites BUILDIFIER_BIN and BUILDOZER_BIN.

We have been using this workaround:

```
ln -s $HOME/go/bin/buildifier /usr/local/bin/buildifier
ln -s $HOME/go/bin/buildozer /usr/local/bin/buildozer
```

Signed-off-by: qqustc <qqin@google.com>